version: "3.9"

services:
  django_test_task:
    container_name: django-test-task
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/django_test_task
    env_file:
      - .env
    command: > 
      sh -c "python manage.py wait_for_db_script && 
      python manage.py migrate && 
      python manage.py loaddata sample.json &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:$PGDATA
    networks:
      - my_network

volumes:
  db:

networks:
  my_network:
    driver: bridge